function G(a,f,d){function h(){0!=I&&(J=(new Date).getTime()-I)}function k(g){F=F|g;B.narme=F}function m(g){q.a("l2("+g+")");E=E|g;T()?(h(),I=0):0==I&&(I=(new Date).getTime());B.narm=E;q.a("l2e")}function u(g){K=K|g;B.naral=K}var q=new P,c=d&&d.dvObj||window.$dv,n=d&&d.impressionId||window.$uid,w=window.Sf||f,x=Array(w.ib),b=w.Xa/w.Wb+1,e=null,l="",v={},g=0,p=Array(w.ib),r={ca:{I:null,J:null,C:null,B:null,Qe:!1},f:{v:null,u:null,K:null,L:null,F:null,G:null,o:null,j:null,Qe:!1},va:{Ab:null,zb:null},
Fb:0},t={},C={},A,y,z={},M={},N=null,Q=!1;this.Ef=function(g){N=g};for(f=0;f<w.ib;f++)p[f]="b"+f;var D={};d&&c&&c.CommonData&&(D.ctx=d.kb,D.cmp=d.jb,D.btreg=d.btreg,D.btadsrv=d.Qa,D.uid=d.pb,D.brid=c.CommonData.BrowserId,D.brver=c.CommonData.BrowserVersion,D.tstype=c.CommonData.Scenario);D.jsver=a?a:null;var B={},H={},I=0,J="",L="",K=0,E=0,F=0,O=0;this.Pc=function(){return I};this.sd=function(g){O=O|g;B.vct=O};this.rd=function(g){e=g;H.strp=e;this.rd=function(){}};this.$b=function(){return(new Date).getTime()};
var U=this.$b();this.Ge=function(){return U};this.sf=function(){E=E&-3;F=F&-2;F&=-3};this.Cb=function(){m(2)};this.Df=function(){k(8);this.qc()};this.qc=function(){m(4)};this.nd=function(){u(8);this.Cb()};this.yd=function(g){u(16);B.dbg9=g};this.zd=function(){u(1)};this.Bf=function(){this.Cb();k(1)};this.Af=function(){this.Cb();k(2)};this.$a=function(g,b){m(8);L=q.ye(g,b)};this.xf=function(){q.a("l1");E=E&-3;m(1);q.a("l1e")};this.qd=function(){m(16)};this.se=function(){return x};this.od=function(e,
p){n=n||d&&d.impressionId||window.$uid;q.a("ie15");if(0<=e.m){var l=Math.floor(e.m/w.Wb);0<e.m%w.Wb?l++:0<e.m&&l++;isNaN(x[l])&&(x[l]=0);x[l]+=p;e.O&&l>=b||0==e.O&&6<=l?g+=p:timeStampTotalBuckets=g=0}q.a("ie15e")};this.zf=function(g){var b=g.Wc;null!=g.Wc&&(t.advisonl=b);null!=g.Vc&&(t.adabvvponl=g.Vc);B.dbg8="CSS1Compat"===document.compatMode?1:0;q.a("ff52");void 0!=document.documentMode&&null!=document.documentMode&&(B.dbg10=document.documentMode);q.a("ff52e")};this.Za=function(g){q.a("ie14");null!=
g&&(M.adbtftopg=g)};this.yf=function(g){null!=g&&(r=g)};this.pd=function(g){q.a("ie19");this.yf(g.s);this.Gf();q.a("ie19e")};this.Cd=function(){null!=r.ca.I&&(z.vptoscrx=Math.round(r.ca.I));null!=r.ca.J&&(z.vptoscry=Math.round(r.ca.J));null!=r.ca.C&&(z.vpwdth=Math.round(r.ca.C));null!=r.ca.B&&(z.vphgt=Math.round(r.ca.B));null!=r.f.v&&(z.adtovpx=Math.round(r.f.v));null!=r.f.u&&(z.adtovpy=Math.round(r.f.u));null!=r.f.K&&(z.adtopgx=Math.round(r.f.K));null!=r.f.L&&(z.adtopgy=Math.round(r.f.L));null!=
r.f.F&&(z.adtoscrx=Math.round(r.f.F));null!=r.f.G&&(z.adtoscry=Math.round(r.f.G));null!=r.va.Ab&&(z.scrwdth=Math.round(r.va.Ab));null!=r.va.zb&&(z.scrhgt=Math.round(r.va.zb));z.almesind=r.Fb};this.Dd=function(){if(A&&y){var g=r.f.o,b=r.f.j;A*y<g*b&&(C.dvp_adwdth=Math.round(A),C.dvp_adhgt=Math.round(y),!Q&&(1>=A||1>=y)&&1<g&&1<b&&($dv.registerEventCall(n,{adwdth:Math.round(g),adhgt:Math.round(b)}),Q=!0),A=g,y=b)}else A=null!=r.f.o?r.f.o:null,y=null!=r.f.j?r.f.j:null;null!=A&&(C.adwdth=Math.round(A));
null!=y&&(C.adhgt=Math.round(y))};this.Gf=function(){h();for(var g=0;g<x.length;g++)x[g]&&(v[p[g]]=x[g]);this.Cd();this.Dd();q.D(z,t);q.D(z,C);q.D(z,M)};this.Nc=function(){return 1E3<=g};this.Ce=function(g){var b={};n=n||d&&d.impressionId||window.$uid;var e=-1,p=q.ze();try{c&&c.tags[n]&&c.tags[n].getTimeDiff&&(e=c.tags[n].getTimeDiff())}catch(a){}var w=[];q.D(b,D);switch(g){case 1:l=e;q.D(b,H);q.D(b,B);b.napt=J;q.D(b,z);b.dvp_log=p;b.napr=L;b.ismms=l;b.isumms=e;break;case 2:q.D(b,H);q.D(b,B);b.napt=
J;q.D(b,z);b.dvp_log=p;b.napr=L;b.isnmms=e;break;case 3:b.istoms=e,b.nvr=N;case 4:case 8:q.D(b,H);q.D(b,M);q.D(b,C);b.isbxdms=e;q.D(b,v);b.nvr=N;break;case 5:q.D(b,H);q.D(b,M);q.D(b,C);q.D(b,t);b.ismms=l||e;b.isiabvms=e;b.isuiabvms=e;break;case 16:q.D(b,H);q.D(b,B);b.napt=J;b.dvp_log=p;b.napr=L;b.ishems=e;break;case 7:return w.join("");default:q.D(b,H),q.D(b,v),q.D(b,B),q.D(b,t),b.napt=J,b.dvp_log=p,b.napr=L}b.evid=g;b.ctime=this.$b();return b};this.re=function(){q.a("ie17");for(var g=[],b=0;b<w.ib;b++)g[b]=
x[b]?x[b]:0;return g};var T=this.Hc=function(){return 2==(E&2)&&8!=(K&8)||4==(E&4)||8==(F&8)&&8==(K&8)?!1:!0};this.kf=function(g){q.a("l3");g=q.fa(g);q.a("cm3e");g&&(B.dbg5=g.w,B.dbg6=g.h);q.a("l3e")};return this}function R(a,f){var d=new P,h=a&&a.impressionId||window.$uid;this.ba=function(a,m){if(f){var u=f.Ce(a);m&&d.D(u,m);var q=!1;if(4==a||8==a)q=!0;this.md(h,u,q)}};this.md=function(a,f,d){$dv&&$dv.registerEventCall&&a&&$dv.registerEventCall(a,f,null,!d,d)}}
function S(){this.ba=function(){};this.md=function(){}}
function V(a,f,d,h){function k(){if(1==r){try{for(var b in g)p.removeChild(g[b]);l.document.body.removeChild(p)}catch(e){}r=!1}}function m(g){g=g||0;var b=c(0);b.Zc()?7<b.ob()?(k(),C=t=r=!1):(r=!0,t=!1):20>g?(g++,setTimeout(m,50,g)):(r=t=C=!1,k())}function u(g){$dv&&$dv.tags&&$dv.tags[h]&&$dv.tags[h].getTimeDiff&&$dv.tags[h].getTimeDiff();if(null!==g.gb)for(var b=0;b<g.gb.length;b++){var e=c(b).ob();0==b?e>A&&(A=e):e>y&&(y=e)}}function q(g){for(var b=!0,e=0;13>=e;e++)var p=c(e),b=b&(null!==p&&p.Zc());
if(!b)return null;g.Ec=0;g.oc=0;g.nc=0;g.hc=0;g.Ba=0;g.gb=Array(13);b=c(0).ob();for(e=1;13>=e;e++)if(p=5<Math.abs(c(e).ob()-b),g.gb[e]=p)switch(g.Ec++,e){case 2:case 3:case 4:case 5:g.oc++;break;case 6:case 7:case 8:case 9:g.nc++;break;case 10:case 11:case 12:case 13:g.hc++}if(13===g.Ec)return g.Ba=100,u(g),!0;b=g.gb;if(!1===b[1]){if(3<=g.hc||3<=g.nc||3<=g.oc)return u(g),null;g.Ba=0;u(g);return!1}if(!0===b[1]&&(!0===b[2]&&!0===b[3]||!0===b[2]&&!0===b[4]||!0===b[3]&&!0===b[5]||!0===b[4]&&!0===b[5])||
!0===b[1]&&4==g.nc||!0===b[1]&&4==g.hc&&1<=g.oc)return g.Ba=50,u(g),!0;if(b[2]&&b[5]&&!(b[6]&&b[10]&&b[1]&&b[13]&&b[9])||b[4]&&b[3]&&!(b[8]&&b[12]&&b[1]&&b[11]&&b[7]))return u(g),null;g.Ba=0;u(g);return!1}function c(b){b=g[b];var e=null;b&&(e=b.contentWindow);return e}function n(){for(var e=v.getBoundingClientRect(),p=e.width,l=e.height,a=p/(1+x),c=l/(1+x),w=p/x,r=l/x,f=0;13>=f;f++){var d=e.left,t=e.top;switch(f){case 0:t=d=-1E5;break;case 1:d+=(p-b)/2;t+=(l-b)/2;break;case 3:d+=p-b;break;case 4:t+=
l-b;break;case 5:d+=p-b;t+=l-b;break;case 6:d+=(p-w)/2;t+=(l-r)/2;break;case 7:d+=(p-w)/2+w;t+=(l-r)/2;break;case 8:d+=(p-w)/2;t+=(l-r)/2+r;break;case 9:d+=(p-w)/2+w;t+=(l-r)/2+r;break;case 10:d+=(p-a)/2;t+=(l-c)/2;break;case 11:d+=(p-a)/2+a;t+=(l-c)/2;break;case 12:d+=(p-a)/2;t+=(l-c)/2+c;break;case 13:d+=(p-a)/2+a,t+=(l-c)/2+c}6<=f&&(d-=b/2,t-=b/2);var n=g[f];n.style.left=d+"px";n.style.top=t+"px"}}function w(){if(null!=v&&null!=v.parentNode){t=!0;p=l.document.createElement("div");l.document.body.appendChild(p);
for(var e=0;13>=e;e++){var a=l.document.createElement("iframe");a.width=b;a.height=b;a.style.position="absolute";a.frameBorder="0";a.style.visibility="hidden";a.style.zIndex=-9999999;a.style.display="block";a.src="javascript:no=false;yes=true;("+function(){window.cf={$d:100};window.Lc=no;window.cb=0;window.Uc=0;window.bd=0;window.Vf=no;window.ob=function(){return window.bd};window.Zc=function(){return window.Lc};window.Xe=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;window.Rb=function(){window.cb++;window.Xe(window.Rb,document)};window.Rb();setInterval(function(){10>window.cb&&window.Rb();window.bd=window.cb-window.Uc;window.Uc=window.cb},window.cf.$d);window.setTimeout(function(){window.Lc=yes},250)}.toString()+")();";p.appendChild(a);g.push(a)}n()}}var x=Math.sqrt(2),b=1,e=new P,l=null,v=null,g=[],p,r=!1,t=!1,C=e.ub(a,f,d);0==e.Va()&&(b=8);var A=0,y=0;this.Me=function(){0==t&&(0==(this.Wa()&&(null!=v&&e.Yc(v,l)?!0:!1))?r=!1:(w(),
m()))};this.Wa=function(){return C};this.Te=function(){return r};this.td=function(g,b){l=g;v=b;this.Me()};this.Je=function(){if(0==r)return null;var g={};return null==q(g)?null:g.Ba}}
function W(a,f,d,h,k,m,u,q){this.b=new P;this.window=a;this.c=f;this.R=d;this.M=h;this.Z=u&&u.Enums.BrowserId||window.$dv.Enums.BrowserId;this.W=u&&u.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario;this.N=k;this.gc=m;this.ea=null;this.Tc=this.window?this.b.vb(this.window.top):this.b.vb(window.top);this.Pe=this.R!=this.W.CrossDomain&&this.b.mb("ofs")&&this.Tc;this.ea=new V(this.R,this.M,u,q);null!=this.ea&&this.ea.Wa()&&this.ea.td(this.window,this.c);this.rb=this.wb=this.pa=null;this.Ua=!1;
var c=0;this.ha={Od:1,Pd:2,Jd:4,Kb:8,Id:16,Lb:32,Nd:64};this.pc=function(a,c,b,e){if(e&&e.insertBefore&&e.firstChild&&(a=this.window.document.createElement(a))){for(var l in c)a[l]=c[l];for(l in b)a.style[l]=b[l];e.insertBefore(a,e.firstChild);return a}return null};this.pe=function(a,c,b){var e=this.window.top,l=a.width,v=a.height;0>b.left?(l=a.width-Math.abs(b.left),0>c.za&&(l-=Math.abs(c.za))):0>c.za&&(l=a.width-Math.abs(c.za)+b.left,l=l>a.width?a.width:l);var g=a.width,p=Math.min(this.b.xa(e.window).clientWidth,
e.innerWidth),d=screen.availWidth-p-c.za,t=0;l<g?(g=l,t=p-l,0>c.za&&(t-=Math.abs(c.za))):t=p-g-b.left;0>t?(l=g-Math.abs(t),0>d&&(l-=Math.abs(d))):0>d&&(l=g-Math.abs(d)+t,l=l>g?g:l);c=screen.availHeight-c.tf-e.outerHeight;e=Math.min(this.b.xa(e.window).clientHeight,e.innerHeight)-a.height-b.top;0>e?(v=a.height-Math.abs(e),0>c&&(v-=Math.abs(c))):0>c&&(v=a.height-Math.abs(c)+e,v=v>a.height?a.height:v);0>b.top&&(v-=Math.abs(b.top));return{Jf:l,Kf:v}};this.Zb=function(a,c,b,e){var l=b.C,v=b.B,g=0;b=0;
var p={width:c.right-c.left,height:c.bottom-c.top};if(0>c.bottom||0>c.right||c.top>v||c.left>l||0>=p.width||0>=p.height)return 0;0>c.top?Math.abs(c.top)>=p.height?g=0:(g=p.height+c.top,g>v&&(g=v)):g=c.top+p.height>v?v-c.top:p.height;0>c.left?Math.abs(c.left)>=p.width?b=p.width:(b=p.width+c.left,b>l&&(b=l)):b=c.left+p.width>l?l-c.left:p.width;this.Pe&&(a=this.pe(p,a,c),b=a.Jf,g=a.Kf);return 0>=b||0>=g?0:Math.round(b*g/(p.width*p.height)*(e?p.width*p.height/((e.right-e.left)*(e.bottom-e.top)):1)*100)};
this.Yb=function(a,c){try{var b={x:a.offsetLeft,y:a.offsetTop},e;a.offsetParent?(e=this.Yb(a.offsetParent,c),b.x+=e.x,b.y+=e.y):c!=c.parent&&this.b.Mb(c,c.parent)&&(e=this.Yb(c.frameElement,c.parent),b.x+=e.x,b.y+=e.y);return b}catch(l){return{x:null,y:null}}};var n=this.b.tb();this.ma=function(a){if(this.R==this.W.CrossDomain)if(this.b.ua(this.window)&&this.window.$sf.ext.geom)this.ma=function(){var g=this.b.Ka(this.window),b=window.outerHeight||this.window.document.documentElement.clientHeight?
this.window.outerHeight-parseInt(g.win.h):this.N.Explorer.X,e={C:null,B:null,I:null,J:null,i:!1};e.C=parseInt(g.win.w);e.B=parseInt(g.win.h);e.I=parseInt(g.win.l);e.J=parseInt(g.win.t)+b;e.i=!0;return e};else if(this.M.Y==this.Z.Firefox)this.ma=function(){var g=8==screen.top-this.window.screenY&&8==screen.left-this.window.screenX,b=g?0:this.window.screenX-screen.left,g=g?0:this.window.screenY-screen.top,e={C:null,B:null,I:null,J:null,i:!1};e.C=this.window.outerWidth;e.B=this.window.outerHeight-this.N.Firefox.X;
e.I=b;e.J=g+this.N.Firefox.X;e.i=!0;return e};else if(this.b.kc(this.window)){var c=this;this.window.context.observeIntersection(function(g){g.forEach(function(g){c.pa=g})});this.ma=function(){var g={C:null,B:null,i:!1,I:null,J:null};null!=this.pa?(g.C=this.pa.rootBounds.width,g.B=this.pa.rootBounds.height):(g.C=0,g.B=0);g.i=!0;return g}}else if(this.M.Y==this.Z.IE&&10<=parseInt(this.M.sa))n&&this.yb(),this.ma=function(){var g=-8==this.window.screenY&&-8==this.window.screenX,b=g?0:this.window.screenX,
g=g?0:this.window.screenY,e={C:null,B:null,I:null,J:null,i:!1};e.C=this.window.outerWidth;e.B=this.window.outerHeight-this.N.Explorer.X;e.I=b;e.J=g+this.N.Explorer.X;n?(this.Ua||this.yb(),e.i=!1):e.i=!0;return e};else if(this.M.Y==this.Z.IE&&/[6-9]|[10]/.test(this.M.sa)){var b=this.pc("iframe",{name:"dv_ie9onload",src:"",width:0,height:0,ke:0,Ye:"0",Ze:"0"},{display:"inline",position:"absolute",top:0,left:0,If:"none",zIndex:0,border:0},this.window.document.body),e=this.pc("iframe",{name:"dv_ie9onmousemove",
src:"",width:0,height:0,ke:0,Ye:"0",Ze:"0"},{display:"inline",position:"absolute",top:0,left:0,If:"none",zIndex:0,border:0},this.window.document.body),l=e.contentWindow||e.window||e.contentDocument.window||e.contentWindow.window||this.window.Nf,v=b.contentDocument||b.contentWindow.document,b=e.contentDocument||e.contentWindow.document,g="<html><head><script >window.onload = "+function(g){g&&(window.event=g);isFinite(String(window.event.clientY))&&(parent.Ra={Pb:window.event.clientY,Ob:window.event.clientX,
Bd:window.event.screenY-window.event.clientY-window.screenY})}.toString()+"; \x3c/script></head><body></body></html>",e='<html><head></head><body><script > function runMoM(){ window.document.body.fireEvent("onmousemove");} window.document.body.onmousemove = '+function(g){g&&(window.event=g);isFinite(String(window.event.clientY))&&(parent.qa={Pb:window.event.clientY,Ob:window.event.clientX,Ga:window.event.screenY-window.event.y,Fa:window.event.screenX-window.event.x})}.toString()+"; runMoM();\x3c/script></body></html>";
b.open("text/html","replace");b.write(e);b.close();v.open("text/html","replace");v.write(g);v.close();("CSS1Compat"===document.compatMode?this.window.document.documentElement:this.window.document.body).clientLeft;this.ma=function(){l.runMoM();v.open("text/html","replace");v.write(g);v.close();var b=this.window.qa,e=this.window.Ra,a=screen.availWidth,c=screen.availHeight,e=e?e.Bd:this.N.Explorer.X;if(b){var d=b.Fa,w=b.Ga;b.Fa>=a&&(b.Fa-=a);b.Ga>=c&&(b.Ga-=c);var f={C:null,B:null,I:null,J:null,i:!1};
f.C=this.window.outerWidth?this.window.outerWidth-20:a-b.Fa-20;f.B=this.window.outerHeight?this.window.outerHeight-e-10:c-b.Ga-10;f.I=d;f.J=w;f.i=!0}else f={C:null,B:null,I:null,J:null,i:!1},f.C=this.window.outerWidth?this.window.outerWidth-20:a-20,f.B=this.window.outerHeight?this.window.outerHeight-e-10:c-10,f.I=null,f.J=null,f.i=!1;return f}}else this.b.tb()?(this.yb(),this.ma=function(){this.Ua||this.yb();var g={C:null,B:null,I:null,J:null,i:!1};g.C=this.window.outerWidth;g.B=this.window.outerHeight-
this.N.Chrome.X;g.i=!1;return g}):this.ma=this.M.Y==this.Z.Chrome?function(){var g={C:null,B:null,I:null,J:null,i:!1},b=!1;try{g.C=this.window.frameElement.offsetParent.parentNode.clientWidth,g.B=this.window.frameElement.offsetParent.parentNode.clientHeight,b=!0}catch(e){}g.I=this.window.screenX;g.J=this.window.screenY;g.i=b;return g}:null!=this.ea&&this.ea.Wa()?function(){var g={C:null,B:null,I:null,J:null,i:!1};g.C=this.window.outerWidth;g.B=this.window.outerHeight-this.N.Safari.X;g.i=!1;return g}:
function(){return{C:null,B:null,I:null,J:null,i:!1}};else this.ma=function(){var g,b,e=this.window.top;void 0!=e.mozInnerScreenX&&null!=e.mozInnerScreenX?(g=e.mozInnerScreenX,b=e.mozInnerScreenY):void 0!=e.screenX&&null!=e.screenX?0!=e.screenLeft+8&&e.screenLeft+8!=screen.width||0!=e.screenTop+8&&e.screenTop+8!=screen.height?(g=e.screenLeft,b=e.screenTop+(e.outerHeight-e.innerHeight)):(g=e.screenLeft+8,b=e.screenTop+(e.outerHeight-e.innerHeight)+8):(g=e.screenLeft,b=e.screenTop);var a={C:null,B:null,
I:null,J:null,i:!1},c=this.b.xa(e);a.C=e.innerWidth||c.clientWidth;a.B=e.innerHeight||c.clientHeight;a.I=g;a.J=b;a.i=!0;return a};return this.ma(a)};this.la=function(a,d){c=1;this.R==this.W.CrossDomain?this.b.ua(this.window)&&this.window.$sf.ext.geom&&this.b.Ka(this.window).par?(c=8,this.la=function(){var b=this.b.Ka(this.window),e=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(b.win.h):this.N.Explorer.X,a={v:null,u:null,K:null,L:null,F:null,
G:null,o:null,j:null,i:!1,rect:null,P:null,oa:null};a.v=parseInt(b.self.l)-parseInt(b.par.l);a.u=parseInt(b.self.t)-parseInt(b.par.t);a.K=parseInt(b.self.l);a.L=parseInt(b.self.t);a.F=parseInt(b.win.l)+a.v;a.G=parseInt(b.win.t)+a.u+e;a.o=parseInt(b.self.w);a.j=parseInt(b.self.h);a.i=!0;a.rect={top:a.u,bottom:a.u+a.j,left:a.v,right:a.v+a.o};return a}):this.M.Y==this.Z.Firefox?this.la=function(){var b=1;window.devicePixelRatio&&(b=window.devicePixelRatio);var e=this.window.screenX,a=this.window.screenY,
c=this.window.mozInnerScreenX/b-e,b=this.window.mozInnerScreenY/b-a-this.N.Firefox.X,c={left:c,top:b,right:c+this.window.innerWidth,bottom:b+this.window.innerHeight},b={v:null,u:null,K:null,L:null,F:null,G:null,o:null,j:null,i:!1,rect:null,P:null,oa:null};b.v=c.left;b.u=c.top;b.K=null;b.L=null;b.F=e+c.left;b.G=a+c.top;b.o=this.window.innerWidth;b.j=this.window.innerHeight;b.i=!0;b.rect=c;this.b.Eb()&&(b=this.lb(b));return b}:this.b.kc(this.window)?(c=32,this.la=function(){var b={v:null,u:null,o:null,
j:null,i:!1,rect:null,P:null,oa:null,K:null,L:null,F:null,G:null};null!=this.pa?(b.v=this.pa.boundingClientRect.left,b.u=this.pa.boundingClientRect.top,b.o=this.pa.boundingClientRect.width,b.j=this.pa.boundingClientRect.height):(b.v=0,b.u=0,b.o=0,b.j=0);b.i=!0;b.rect={top:b.u,bottom:b.u+b.j,left:b.v,right:b.v+b.o};return b}):this.M.Y==this.Z.IE&&10<=parseInt(this.M.sa)?this.la=function(b){var e=this.window.screenLeft-window.screenX,a=this.window.screenTop-window.screenY-this.N.Explorer.X,e={left:e,
top:a,right:e+this.window.innerWidth,bottom:a+this.window.innerHeight},a={v:null,u:null,K:null,L:null,F:null,G:null,o:null,j:null,i:!1,rect:null,P:null,oa:null};a.v=e.left;a.u=e.top;a.K=null;a.L=null;a.F=b.I+e.left;a.G=b.J+e.top;a.o=this.window.innerWidth;a.j=this.window.innerHeight;a.i=!n;a.rect=e;this.b.Eb()&&(a=this.lb(a));return a}:this.M.Y==this.Z.IE&&/[6-9]|[10]/.test(this.M.sa)?this.la=function(){if(8==document.documentMode)return{v:null,u:null,K:null,L:null,F:null,G:null,o:null,j:null,i:!1,
rect:null,P:null,oa:null};var b=this.window.Ra&&this.window.qa?this.window.Ra.Pb-this.window.qa.Pb:0,e=this.window.Ra&&this.window.qa?this.window.Ra.Ob-this.window.qa.Ob:0,a=this.b.xa(this.window),c={v:null,u:null,K:null,L:null,F:null,G:null,o:null,j:null,i:!1,rect:null,P:null,oa:null};c.v=e;c.u=b;c.K=null;c.L=null;c.F=this.window.qa?e+this.window.qa.Fa:null;c.G=this.window.qa?b+this.window.qa.Ga:null;c.o=this.window.innerWidth||a.clientWidth;c.j=this.window.innerHeight||a.clientHeight;c.i=!0;c.rect=
{left:e,top:b,right:e+(this.window.innerWidth||a.clientWidth),bottom:b+(this.window.innerHeight||a.clientHeight)};this.b.Eb()&&(c=this.lb(c));return c}:this.b.tb()?(c=512,this.la=function(){var b={v:null,u:null,K:null,L:null,F:null,G:null,o:null,j:null,i:!1,rect:null,P:null,oa:null};null!=this.c&&(adData=this.b.nb(this.c),b.o=adData?adData.w:this.window.innerWidth,b.j=adData?adData.h:this.window.innerHeight);return b}):this.la=this.M.Y==this.Z.Chrome?function(){var b=null,e=null,a=!1;try{var c=this.window.frameElement.offsetTop,
b=this.window.frameElement.offsetLeft-this.window.frameElement.offsetParent.scrollLeft,e=c-this.window.frameElement.offsetParent.scrollTop,a=!0}catch(g){}c={v:null,u:null,K:null,L:null,F:null,G:null,o:null,j:null,i:!1,rect:null,P:null,oa:null};c.v=b;c.u=e;c.K=null;c.L=null;c.F=null;c.G=null;c.o=this.window.innerWidth;c.j=this.window.innerHeight;c.i=a;c.rect=a?{left:b,top:e,right:b+this.window.innerWidth,bottom:e+this.window.innerHeight}:null;this.b.Eb()&&(c=this.lb(c));return c}:null!=this.ea&&this.ea.Wa()?
function(){var b={v:null,u:null,K:null,L:null,F:null,G:null,o:null,j:null,i:!1,rect:null,P:null,oa:null};null!=this.c&&(adData=this.b.nb(this.c),b.o=adData?adData.w:this.window.innerWidth,b.j=adData?adData.h:this.window.innerHeight);return b}:function(){return{v:null,u:null,K:null,L:null,F:null,G:null,o:null,j:null,i:!1,rect:null,P:null,oa:null}}:this.la=function(b){var e=this.Yb(this.c,this.window),a={v:null,u:null,K:null,L:null,F:null,G:null,o:null,j:null,i:!1,rect:null,P:null,oa:null},c=this.b.ac(this.c,
this.window),g=this.b.vc(this.c,this.window);a.v=g.left;a.u=g.top;a.K=e.x;a.L=e.y;a.F=b.I+g.left;a.G=b.J+g.top;a.o=g.w;a.j=g.h;a.i=!0;a.rect=c;a.P=g;return a};return this.la(a,d)};this.lb=function(a){if(this.window.document.body==this.c||this.window.document.documentElement==this.c)return a;var c=this.b.nb(this.c);if(c){var b=c.w,e=c.h,l=a.v,d=a.u,g=a.G,p=a.F;null!=a.v&&null!=a.u&&null!=a.j&&null!=a.o&&a.rect&&(0<c.t?(d=a.u+c.t,null!=a.G&&(g=a.G+c.t)):e+=c.t,0<c.l?(l+=c.l,null!=a.F&&(p=a.F+c.l)):
b+=c.l,c.r>a.o&&(b-=c.r-a.o),c.Dc>a.j&&(e-=c.Dc-a.j),a.o=0<b?b:0,a.j=0<e?e:0,a.v=l,a.u=d,a.G=g,a.F=p,a.rect.left=a.v,a.rect.top=a.u,a.rect.right=a.v+c.w,a.rect.bottom=a.u+c.h,a.P={w:b,h:e,left:l,right:l+b,top:d,bottom:d+e})}return a};this.Fe=function(){var a=screen.availWidth,c=screen.availHeight,b=screen.width,e=screen.height,d=0,f=0;this.Tc&&(f=this.window.top,d=f.screenX,f=f.screenY);return{i:this.N.Va?!1:"undefined"!==typeof d,Ab:a||b,zb:c||e,Tf:d,Uf:f,za:d-(b-a),tf:f-(e-c)}};this.ne=function(){var a=
this.Fe(),c=this.ma(a),b=this.la(c,a);return{ca:c,f:b,va:a,Fb:(null==c.I||null==c.J?0:this.ha.Od)|(null==c.C||null==c.B?0:this.ha.Pd)|(null==b.v||null==b.u?0:this.ha.Jd)|(null==b.K||null==b.L?0:this.ha.Kb)|(null==b.F||null==b.G?0:this.ha.Id)|(null==b.j||null==b.o?0:this.ha.Lb)|(null==a.zb||null==a.Ab?0:this.ha.Nd),O:this.Ic(b.j,b.o)}};this.Ic=function(a,c){null==a&&(a=0);null==c&&(c=0);return 1!=this.N.Va?242500<=a*c:!1};this.ve=function(){this.b.a("c10");if(null!=this.c)if(this.b.Yc(this.c,this.window))try{var a=
{timeStamp:new Date,m:-3,ia:-3,s:null,O:!1,da:0};if(!this.gc())return a;var d=this.ne(),b;if(!d.f.i||!d.ca.i){if(this.b.ua(this.window)&&this.window.$sf.ext.inViewPercentage)return b=this.window.$sf.ext.inViewPercentage(),{timeStamp:new Date,m:b,ia:b,s:d,O:d.O,da:16};if(n&&this.Ua)return b=0,null!=this.rb&&(b=Math.round(100*this.rb.intersectionRatio)),{timeStamp:new Date,m:b,ia:b,s:d,O:this.Ic(d.f.j,d.f.o),da:512};if(this.ea.Wa()){var e={timeStamp:new Date,m:-3,ia:-3,s:null,O:!1,da:2};if(0==this.ea.Te())e.m=
-6,e.ia=-6,this.ea.td(this.window,this.c);else{var l=this.ea.Je();null!=l&&(e.s=d,e.O=d.O,e.m=l,e.ia=l)}return e}a.s=d;c&&(a.da=c);return a}if(d.f&&d.f.P&&(0===d.f.P.w||1===d.f.P.w||0===d.f.P.h||1===d.f.P.h))return{timeStamp:new Date,m:-5,ia:-5,s:d,da:c};b=d.f.P?this.Zb(d.va,d.f.P,d.ca,d.f.rect):this.Zb(d.va,d.f.rect,d.ca);return{timeStamp:new Date,m:b,ia:b,s:d,O:d.O,da:c}}catch(f){return{timeStamp:new Date,m:-4,ia:-4,s:null,O:!1,da:c}}else return{timeStamp:new Date,m:-2,ia:-2,s:null,O:!1,da:0};else return{timeStamp:new Date,
m:-1,ia:-1,s:null,O:!1,da:0}};this.oe=function(a,c){this.b.a("c11");var b=null,e=null;if(null!=a.s){var d=a.s.f;c<=this.N.ef&&(b=0<=a.m||-5==a.m?a.O&&a.m>=this.N.Xa||0==a.O&&50<=a.m?!0:!1:null,e=a.O?this.N.Xa/100:.5,e=0==b?0>d.u+d.j*e?!0:!1:1==b?!1:null)}return{Vc:e,Wc:b}};this.sb=function(a){this.b.a("c12");var c=null;if(2!=a.da&&512!=a.da&&null!=a.s){var b=a.s.Fb,e=a.s.f;(b&this.ha.Kb)==this.ha.Kb&&(b&this.ha.Lb)==this.ha.Lb&&(c=this.Zb(a.s.va,{left:e.K,top:e.L,right:e.K+e.o,bottom:e.L+e.j},a.s.ca,
e.rect),c=0<=a.m?a.O&&c>=this.N.Xa||0==a.O&&50<=c?!1:!0:null)}this.b.a("c12e");return c};this.yb=function(){function a(b){b.forEach(function(b){d.rb=b})}var d=this;"undefined"!=typeof IntersectionObserver&&null!=this.c&&(c=512,this.wb=new IntersectionObserver(a,{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]}),this.wb.observe(this.c),this.Ua=!0)};this.Le=function(){this.c=null;null!=this.wb&&(this.wb.disconnect(),this.rb=null,this.Ua=!1)}}
function P(){this.getElementVolume_object=function(a){var f=a.getAttribute("width"),d=a.getAttribute("height");null==f||""==f||null==d||""==d?(a=a.parentNode,a={w:a.clientWidth,h:a.clientHeight}):a={w:f,h:d};return a};this.Ue=function(a){var f=0;try{for(;null!=a&&10>f;){if("none"==window.getComputedStyle(a).display||"hidden"==window.getComputedStyle(a).visibility)return!1;a=a.parentElement;f++}}catch(d){}return!0};this.fa=function(a,f){this.a("cm1");var d=null,h=a.nodeName.toLowerCase();f&&this["getElementVolume_"+
h]&&(d=this["getElementVolume_"+h](a));if(!d&&(d=this.nb(a),this.a("cm2e"),!d||1>=d.w||1>=d.h))return this.a("cm1e"),{w:0,h:0};d.w.indexOf&&d.w.indexOf("px")&&(d.w=d.w.replace("px",""));d.h.indexOf&&d.h.indexOf("px")&&(d.h=d.h.replace("px",""));this.a("cm1e");return d};this.nb=function(a){this.a("cm2");try{var f;return document.body.getBoundingClientRect&&(f=a.getBoundingClientRect())?{w:f.right-f.left,h:f.bottom-f.top,l:f.left,t:f.top,Dc:f.bottom,r:f.right}:null}catch(d){return null}};this.xa=function(a){return a.document.documentElement.clientHeight?
a.document.documentElement:a.document.body};this.Oc=function(a,f){this.a("ff9");var d=0,h=!1;if(a.document.all)for(var k=0;k<a.document.all.length;k++)"BODY"==a.document.all[k].nodeName&&(h=!0),h&&("width"==f?a.document.all[k].width>d&&(d=a.document.all[k].width):a.document.all[k].height>d&&(d=a.document.all[k].height));this.a("ff9e");return d};this.ad=function(a,f){for(var d=this.xa(a),h=a.innerWidth||d.clientWidth||this.Oc(a,"width"),d=a.innerHeight||d.clientHeight||this.Oc(a,"height"),k=f.length,
m=0,u=0;u<k;u++)if(15>=Math.abs(h-f[u].w)){m=f[u].h.length;for(h=0;h<m;h++)if(15>=Math.abs(d-f[u].h[h]))return!0;break}return!1};this.Hf=function(a){for(var f=[],d=-1;f[++d]=a[d];);f.length--;return f};this.Hb=function(a,f,d,h){var k=a.getElementsByTagName("*"),k=this.Hf(k);k.unshift(a);for(var m="EMBED IFRAME OBJECT IMG DIV SVG CANVAS".split(" "),u=[],q=0;q<k.length;q++){var c=k[q];if(-1!=m.indexOf(c.nodeName.toUpperCase())){var n=h(c);n&&u.push({Cc:n.w*n.h,w:n.w,h:n.h,type:c.nodeName||"other",je:c})}}u=
u.sort(function(a,c){return c.Cc-a.Cc||m.indexOf(c.type)-m.indexOf(a.type)});(f=0<u.length&&u[0].w>f&&u[0].h>d?u[0].je:null)&&a&&(f.qb=a.qb);!f||"canvas"!=f.nodeName.toLowerCase()&&"svg"!=f.nodeName.toLowerCase()||$dv.registerEventCall($uid,{dvp_cnvsvg:"div_"+f.nodeName.toLowerCase()});return f};this.Yc=function(a,f){this.a("ff10");try{if(!a)return!1;for(f||(f=window);a!=f.document&&a.parentNode;)a=a.parentNode;this.a("ff10e");return a==f.document}catch(d){return!1}};this.ac=function(a,f){var d=f.parent,
h={left:0,right:0,top:0,bottom:0};if(a){var k=a.getBoundingClientRect();f!=d&&this.Mb(f,d)&&(h=this.ac(f.frameElement,d));h={left:k.left+h.left,right:k.right+h.left,top:k.top+h.top,bottom:k.bottom+h.top}}return h};this.Mb=function(a,f){var d=!1;if(a==f)d=!0;else try{a.document.domain==f.document.domain&&(d=!0)}catch(h){}return d};this.we=function(a){if(a)try{if(a.contentDocument&&this.Xc(a.contentDocument))return a.contentDocument;if(a.contentWindow&&this.vb(a.contentWindow))return a.contentWindow.document}catch(f){}return null};
this.Sc=function(a){return a?a.defaultView||a.parentWindow:null};this.Oe=function(a,f){return-1<f.indexOf(a)};this.qe=function(a){try{return a!=a.top&&a.parent&&this.vb(a.parent)?a.parent:null}catch(f){return null}};this.vb=function(a){try{return a&&a.document&&this.Xc(a.document)?!0:!1}catch(f){return!1}};this.Xc=function(a){try{return a&&a.getElementsByTagName&&a.getElementById?!0:!1}catch(f){return!1}};this.vc=function(a,f){var d=f.parent,h={w:0,h:0,left:0,right:0,top:0,bottom:0};a&&(h=this.ac(a,
f),h.w=h.right-h.left,h.h=h.bottom-h.top,f!=d&&this.Mb(f,d)&&(d=this.vc(f.frameElement,d),d.bottom<h.bottom&&(d.bottom<h.top&&(h.top=d.bottom),h.bottom=d.bottom),d.top>h.top&&(d.top>h.bottom&&(h.bottom=d.top),h.top=d.top),d.right<h.right&&(d.right<h.left&&(h.left=d.right),h.right=d.right),d.left>h.left&&(d.left>h.right&&(h.right=d.left),h.left=d.left),h.w=h.right-h.left,h.h=h.bottom-h.top));return h};this.Sb=function(a,f){return function(){return a.apply(f,arguments)}};this.ta=function(a){try{return a?
a.length?a.length:0:0}catch(f){return 0}};this.ec=function(a){for(var f=[],d=0;d<a.length;d++)this.Ue(a[d])&&f.push(a[d]);return f};this.a=function(a){try{maxLength=3,$dv&&($dv.La=$dv.La||[],$dv.La.push(a),$dv.La.length>maxLength&&$dv.La.shift())}catch(f){}};this.ze=function(){try{return $dv&&$dv.La?$dv.La.join():""}catch(a){return""}};this.ua=function(a){if(a.$sf&&a.$sf.ext)if(a.$sf.ext.geom){if(a=this.Ka(a),null!=a&&a.win&&(0<a.win.h||0<a.win.w))return this.ua=function(){return!0},!0}else if(a.$sf.ext.inViewPercentage)return!0;
this.ua=function(){return!1};return!1};this.Ka=function(a){a.$sf.ext.geom&&(this.Ka="function"==typeof a.$sf.ext.geom?function(a){return a.$sf.ext.geom()}:function(a){return a.$sf.ext.geom});return this.Ka(a)};this.D=function(a,f){if(null!=a&&null!=f)for(var d in f)f.hasOwnProperty(d)&&(a[d]=f[d])};this.kc=function(a){return a.context&&a.context.observeIntersection?!0:!1};this.tb=function(){var a=!1;if(1==this.mb("disableIO"))return!1;"undefined"!=typeof IntersectionObserver&&(a=!0);return a};this.ub=
function(a,f,d){var h=d&&d.Enums.BrowserId||window.$dv.Enums.BrowserId;if(a==(d&&d.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario).CrossDomain&&f.Y===h.Safari&&(null===f.sa||void 0===f.sa||!/^[3-8]/.test(f.sa)))return this.ub=function(){return!0},!0;this.ub=function(){return!1};return!1};this.mb=function(a){var f,d=this.Mc();d&&d.AVO&&(f=d.AVO[a]);return f};this.Mc=function(){var a={},f=window.$dv,d=window.$uid;f.tags&&f.tags[d]&&(a=f.tags[d]);return a};this.Eb=function(){return 1==this.mb("sam")?
!0:!1};this.Ta=function(a){return a.document.hasFocus()};this.Ja=new function(){var a=this;a.cache=[];window.addEventListener?a.add=function(f,d,h,k,m){if("undefined"==typeof k||null==k)k=window;k.addEventListener(f,d,h);m&&a.cache.push([f,d,h,k])}:window.attachEvent?a.add=function(f,d,h,k,m){if("undefined"==typeof k||null==k)k=window;k["e"+f+d]=d;k[f+d]=function(){k["e"+f+d](window.event)};k.attachEvent("on"+f,k[f+d]);m&&a.cache.push([f,d,h,k])}:a.add=function(){};window.removeEventListener?a.remove=
function(a,d,h,k){if("undefined"==typeof k||null==k)k=window;k.removeEventListener(a,d,h)}:window.detachEvent?a.remove=function(a,d,h,k){if("undefined"==typeof k||null==k)k=window;k.detachEvent("on"+a,k[a+d]);k[a+d]=null;k["e"+a+d]=null}:a.remove=function(){};a.flush=function(){for(var f=0;f<a.cache.length;f++)a.remove.apply(a,a.cache[f]);a.cache=[]}};this.getElementsByClassName=function(a,f){return a.getElementsByClassName?a.getElementsByClassName(f):a.querySelectorAll?a.querySelectorAll("."+f):
[]};this.Va=function(){var a=!1;if($dv&&$dv.CommonData){var f=$dv.CommonData.detectedDeliveryType;f&&0!=f?a=2==f||3==f:(f=$dv.CommonData.deviceType)&&(a=2==f||3==f)}return a};this.ye=function(a,f){var d=a||"",h="";if(f&&(d+=": "+(f.message||""),f.stack)){var h=f.stack||"",k=h.indexOf("at ");0>k&&(k=0);h=", Stack: "+h.slice(k,h.length)}d=d.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"");h=h.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"").replace(/    at/g,
"at").replace(/\?/g,"-").replace(/&/g,"-");k=null;try{k=encodeURIComponent(d+h).slice(0,500)}catch(m){try{k=encodeURIComponent(d).slice(0,500)}catch(u){k=d.slice(0,500)}}return k}}
function X(a,f,d,h,k,m){var u=new P;this.g=h;this.window=d;this.c=null;this.dataObj=a;this.dvObj=a.dvObj||window.$dv;this.jc=null;this.M={Y:this.dvObj.CommonData.BrowserId,sa:this.dvObj.CommonData.BrowserVersion};this.Z=this.dvObj.Enums.BrowserId;this.R=k;this.W=this.dvObj.Enums.TrafficScenario;this.ja=f;this.A=m.A;115==this.dataObj.eb&&(this.A.H.h=20,this.A.H.w=20);this.rf=function(){m.jf(this.c);this.c=m.c=null};var q=[],c="object embed img iframe svg canvas".split(" ");this.dataObj.spotXmode&&
(c=["object","embed","video","iframe"]);this.Re=function(a){u.a("a33");a=u.fa(a);return this.Se(a)};this.Se=function(a){if(a){var c=a.w;a=a.h;for(var d=f.length,b=0,e=0;e<d;e++)if(15>=Math.abs(c-f[e].w))for(var b=f[e].h.length,l=0;l<b;l++)if(15>=Math.abs(a-f[e].h[l]))return!0}return!1};this.te=function(){u.a("a34");return this.ue()||this.uf()};this.uf=function(){u.a("a35");var a=(window.name||(window.frameElement?window.frameElement.id:"")).substr(7),c=[],d=window.parent;u.a("ff6");try{c=d.document.getElementsByTagName("script")}catch(e){}u.a("ff6e");
for(var d=c.length,b=0;b<d;b++)if(c[b]&&c[b].id&&c[b].id.substr(7)==a)return c[b];return null};this.ue=function(){u.a("a36");return this.dvObj&&this.dataObj.impressionId&&this.dvObj.tags&&this.dvObj.tags[this.dataObj.impressionId]?this.dvObj.tags[this.dataObj.impressionId].tagElement:null};this.Vd=function(a){u.a("a38");var d={node:a,wa:0};a=[];for(q=[];d||0<a.length;){try{if(1==d.wa){var f=m.lc(d.node);if(f&&!m.na(d.node)&&m.S(d.node))return m.S(f),$dv&&$dv.eventBus&&$dv.eventBus.dispatchEvent&&
$dv.eventBus.dispatchEvent(window,"avsAdFound",{timeStamp:(new Date).getTime(),adDomElement:f}),d.node=f,d}var b;a:{var e=d.node;try{if(e&&-1!=c.indexOf(e.nodeName.toLowerCase())){b=!0;break a}}catch(h){}b=!1}if(b&&this.Re(d.node)&&!m.na(d.node)&&m.S(d.node))return"canvas"!=d.node.nodeName.toLowerCase()&&"svg"!=d.node.nodeName.toLowerCase()||$dv.registerEventCall($uid,{dvp_cnvsvg:"bfs_"+d.node.nodeName.toLowerCase()}),d;if(d.wa<=this.A.af){var l,v=d.node,g=d.wa,d=[],p=v.parentNode;p&&-1==q.indexOf(p)&&
(q.push(p),d.push({node:p,wa:g+1}));if(v.hasChildNodes())for(var r=0;r<v.childNodes.length;r++)v.childNodes[r]&&-1==q.indexOf(v.childNodes[r])&&1===v.childNodes[r].nodeType&&(q.push(v.childNodes[r]),d.push({node:v.childNodes[r],wa:g+1}));var t,k=v,A=[],y=null;k&&k.parentNode&&(y=k.parentNode.firstChild);for(;y;)1===y.nodeType&&y!==k&&A.push(y),y=y.nextElementSibling||y.nextSibling;t=A;for(r=0;r<t.length;r++)t[r]&&-1==q.indexOf(t[r])&&1===t[r].nodeType&&(q.push(t[r]),d.push({node:t[r],wa:g+1}));if(l=
d)for(d=0;d<l.length;d++)a.push(l[d])}}catch(h){}d=a.shift()}return{node:null}};this.Be=function(){u.a("a37");var a=this.te(),c=null;a&&(c=this.Vd(a));return c};this.le=function(a){u.a("a31");if(this.c=m.Ae())return this.g.zd(),this.jc=!0,this.c;if(this.dataObj.btreg&&!0===this.jc&&1<a)return this.c;"1"!=this.dataObj.displaynon&&(a=this.Be())&&a.node&&(this.g.yd(a.wa),this.c=a.node);return this.c};return this}
function aa(a,f,d,h,k,m){function u(b,a){for(var c=[],d=0;d<x.length;d++){var g=[],g=a(b,x[d]),p=n.ta(g);if(0!=p){var f=n.Sc(x[d]);if(null!=f)for(var t=0;t<p;t++)try{g[t].qb=f,c.push(g[t])}catch(h){}}}return c}function q(b,a){return u(b,function(b,c){n.a("ff4");var g=c.getElementsByTagName(b);n.a("ff4e");return"1"!=a?g:n.ec(g)})}var c=this,n=new P,w="Microsoft Internet Explorer"==navigator.appName;this.dataObj=a;this.window=f;this.c=d;this.R=h;this.W=k;this.dvObj=void 0===m?m={}:m;this.A={H:{h:1,
w:1},Lf:{h:10,w:10},af:10};115==this.dataObj.eb&&(this.A.H.h=20,this.A.H.w=20);this.Ee=function(b){if(b.scanOrder)return b.scanOrder;var a=[1==w?"object":"embed",1==w?"embed":"object","href","img","span","iframe","frameElement","div","canvas","svg"];b.findclass&&1==b.findclass&&a.push("classDeclaration");b.hb&&0<b.hb.length&&a.unshift("searchCustomElementsFromTag");return a};this.searchCustomElementsFromTag=function(b){for(var a=0;a<b.hb.length&&(c.Jc(b.hb[a],b),!c.c);a++);};this.Gb=[["DCF",'"'],
[";",";"],["%3B","%3B"],["zoneid=","_"],["zoneid%3D","_"],["PRImpID=",""],["PRImpID%3D",""],["PRPID=",""],["PRPID%3D",""]];this.de=function(){var b=c.dataObj.kb+"-"+c.dataObj.jb;a.isBrandShieldOrigin&&(b+="-bs");return b.replace(RegExp(",","g"),";")};this.rc=this.de();this.Jc=function(b,a){if(a.btreg)for(var d=q(b,a.displaynon),f=n.ta(d),g=0;g<f;g++)if(d[g]&&c.Ca(a,d[g],!0)&&!c.na(d[g])){var p=this.lc(d[g]);if(p&&(r=n.fa(p))&&r.h>c.A.H.h&&r.w>c.A.H.w&&c.S(p)){c.c=p;c.S(d[g]);break}var r=n.fa(d[g]);
if(r&&r.h>c.A.H.h&&r.w>c.A.H.w&&c.S(d[g])){c.c=d[g];break}if((p=n.Hb(d[g],c.A.H.w,c.A.H.h,n.Sb(n.fa,n)))&&c.S(p)){c.c=p;c.S(d[g]);break}}};this.div=function(b){this.Jc("div",b)};this.span=function(b){n.a("a10");if(b.btreg)for(var a=q("span",b.displaynon),d=n.ta(a),f=0;f<d;f++)if(a[f]&&c.Ca(b,a[f],!0)&&!c.na(a[f])){var g=a[f];n.a("a20");if(g&&"1"==g.getAttribute("adunit")){c.c=a[f];break}if(g=this.lc(a[f])){var p=n.fa(g);if(p&&p.h>c.A.H.h&&p.w>c.A.H.w&&c.S(g)){c.c=g;c.S(a[f]);break}}if((g=n.Hb(a[f],
c.A.H.w,c.A.H.h,n.Sb(n.fa,n)))&&c.S(g)){c.c=g;c.S(a[f]);break}}};this.object=function(b){n.a("a11");for(var a=q("object",b.displaynon),d=n.ta(a),f=0;f<d;f++)if(a[f]&&c.Ca(b,a[f])&&!c.na(a[f])){var g=n.Hb(a[f],c.A.H.w,c.A.H.h,n.Sb(n.fa,n));if(g&&c.S(g)){c.S(a[f]);c.c=g;break}}};this.bc=function(a,e){n.a("a14");for(var d=q(e,a.displaynon),f=n.ta(d),g=0;g<f;g++)if(d[g]&&c.Ca(a,d[g])&&!c.na(d[g])){var p=n.fa(d[g]);if(p&&p.h>c.A.H.h&&p.w>c.A.H.w&&c.S(d[g])){c.c=d[g];"canvas"!=e&&"svg"!=e||$dv.registerEventCall($uid,
{dvp_cnvsvg:"btreg_"+e});break}}};this.embed=function(a){n.a("a12");this.bc(a,"embed")};this.href=function(a){n.a("a13");for(var e=q("a",a.displaynon),d=n.ta(e),f=0;f<d;f++)if(e[f]&&c.Ca(a,e[f])&&!c.na(e[f])){var g=e[f].getElementsByTagName("img");if(0<g.length){var p=n.fa(g[0]);if(p&&p.h>c.A.H.h&&p.w>c.A.H.w&&c.S(e[f])){c.c=g[0];break}}}};this.img=function(a){n.a("a31");this.bc(a,"img")};this.canvas=function(a){n.a("a32");this.bc(a,"canvas")};this.classDeclaration=function(a){n.a("a9");var e="undefined"!==
typeof window.document.getElementsByClassName,d="undefined"!==typeof window.document.querySelectorAll;if(a.btreg){var f=[];if(e)f=c.getElementsByClassName(a.btreg,a.displaynon);else if(d)f=c.querySelectorAll(a.btreg,a.displaynon);else return;a=n.ta(f);for(e=0;e<a;e++)if(f[e]&&!c.na(f[e])&&(d=n.fa(f[e]))&&d.h>c.A.H.h&&d.w>c.A.H.w&&c.S(f[e])){c.c=f[e];break}}};this.iframe=function(a){n.a("a15");for(var e=q("iframe",a.displaynon),d=n.ta(e),f=0;f<d&&!c.yc(a,e[f]);f++);};this.frameElement=function(a){try{n.a("a16"),
h==k.SameDomain&&c.yc(a,window.frameElement)}catch(e){}};this.getElementsByClassName=function(a,c){return u(a,function(a,b){n.a("ff1");var g=b.getElementsByClassName(a);n.a("ff1e");return"1"!=c?g:n.ec(g)})};this.querySelectorAll=function(a,c){return u(a,function(a,b){n.a("ff3");var g=b.querySelectorAll("."+a);n.a("ff3e");return"1"!=c?g:n.ec(g)})};this.ka=function(a,e){n.a("a28");return!a||!e||5>e.length?!1:null!=(c.wc?c.wc(a,e):c.Ib(a,e))?!0:c.Tb&&"function"===typeof c.Tb?c.Tb(a,e):!1};this.Ca=function(a,
e,d){n.a("a22");var f=null;return a.btreg&&(c.wc=1==a.Ve?c.Fd:c.Ib,f=c.Ld(a,e,d))||!c.c&&(f=c.Md(a,e))?!0:!1};this.Qd=function(a){n.a("a21");if(a&&!c.na(a)){var e=n.fa(a);if(e&&e.h>c.A.H.h&&e.w>c.A.H.w&&c.S(a))return c.c=a,!0}return!1};this.yc=function(a,e){n.a("a17");return c.Ca(a,e)?c.Qd(e):!1};this.na=function(a){n.a("a19");if(a&&(a=a.getAttribute("dvvisit"))){a=a.split(",");for(var e=0;e<a.length;e++)if(a[e]==c.rc)return!0}return!1};this.S=function(a){n.a("a18");if(a&&0==c.na(a))try{var e=a.getAttribute("dvvisit");
e?a.setAttribute("dvvisit",e+","+c.rc):(n.a("ff5"),e=window.document.createAttribute("dvvisit"),n.a("ff5e"),e.value=c.rc,a.setAttributeNode(e));$dv.eventBus&&window&&$dv.eventBus.dispatchEvent(window,"adLocated",{adElement:a,timeStamp:(new Date).getTime()});return!0}catch(d){}return!1};this.jf=function(a){a&&a.hasAttribute&&a.hasAttribute("dvvisit")&&a.removeAttribute("dvvisit")};this.Fd=function(a,e){n.a("a29");var d;try{d=(new RegExp(e)).exec(a)}catch(f){d=c.Ib(a,e)}return d};this.Ib=function(a,
c){n.a("a30");var d=null;-1!==a.indexOf(c)&&(d=a);return d};this.lc=function(a){var c=null;"celtra-ad-v3"==a.className&&a.celtra&&1==a.celtra.loaded&&(c=a.celtra.viewabilityObservee);c&&(c.qb=n.Sc(c.ownerDocument)||window);return c};var x=[];this.Ld=function(a,d,f){n.a("a23");var h;try{if(a.Gc&&d&&d.hasAttribute&&d.hasAttribute("dv-view"))return!0;(h=c.ka(d.id,a.btreg))||(h=c.ka(d.src,a.btreg));h||(h=c.ka(d.href,a.btreg));h||(h=c.ka(d.getAttribute("flashvars"),a.btreg));h||(h=c.ka(d.name,a.btreg));
!h&&a.findclass&&1==a.findclass&&(h=c.ka(d.getAttribute("class"),a.btreg));if(!h&&c.dataObj.Ia&&0<c.dataObj.Ia.length)for(var g=c.dataObj.Ia,p=0;p<g.length&&!(h=c.ka(d.getAttribute(g[p]),a.btreg));p++);h||f||(h=c.ka(d.innerHTML,a.btreg));h&&!f&&(h=c.Kd(a,d));return h}catch(r){return h}};this.Da=function(a,d){n.a("a25");if(!a)return!1;a=a.toLowerCase();for(var f=0;f<c.Gb.length;f++){var h;if(d.Bc&&(h=(c.Gb[f][0]+d.Bc).toLowerCase(),h=a.indexOf(h),-1<h)||d.gd&&(h=(c.Gb[f][0]+d.gd).toLowerCase(),h=a.indexOf(h),
-1<h))return!0}return!1};this.Md=function(a,d){n.a("a24");var f;try{if(a.Gc&&d&&d.hasAttribute&&d.hasAttribute("dv-view"))return!0;(f=c.Da(d.id,a))||(f=c.Da(d.src,a));f||(f=c.Da(d.href,a));f||(f=c.Da(d.Qf,a));f||(f=c.Da(d.name,a));f||(f=c.Da(d.innerHTML,a));if(!f&&c.dataObj.Ia&&0<c.dataObj.Ia.length)for(var h=c.dataObj.Ia,g=0;g<h.length&&!(f=c.ka(d.getAttribute(h[g]),a.btreg));g++);return f}catch(p){return f}};this.Kd=function(a,d){n.a("a26");return null==a.Qa||""==a.Qa?!1:c.ka(c.Ed(d),a.Qa)};this.searchByAdSrvId_8=
function(a,c){n.a("a1");var d=/[0-9]+-[0-9]+-[0-9]+-[0-9]+/.exec(a);return null!=d&&(d=d.toString(),d.replace(RegExp("-","g"),"")==c)?!0:!1};this.Tb=this["searchByAdSrvId_"+(c.dataObj?c.dataObj.eb||"":"")];this.Ed=function(a){n.a("a27");if(a.outerHTML)return a.outerHTML;for(var c=a.attributes.length,d="",f=0;f<c;f++)d=d+a.attributes[f].nodeName+"="+a.attributes[f].nodeValue+" ";return d+a.innerHTML};this.Ae=function(){n.a("32");var a=[];void 0===m.tags&&(m.tags={});void 0===m.tags[$uid]&&(m.tags[$uid]=
{});void 0!==m.tags[$uid].spvi&&(a.push(m.tags[$uid].spvi),-1<a[0].scanOrder.indexOf(",")&&(a[0].scanOrder=a[0].scanOrder.split(",")));c.dataObj.scanOrder=this.Ee(c.dataObj);a.push(c.dataObj);var e=c.window,f=0,h=[];try{do{h.push(e.document);for(var g=h,p=e.document.getElementsByTagName("iframe")||[],r=0;r<p.length||25>r;r++){var t=null,t=n.we(p[r]);void 0!==t&&null!==t&&0==n.Oe(t,g)&&g.push(t)}e=n.qe(e)}while(e&&10>++f)}catch(q){}x=h;for(e=0;e<a.length;e++)for(f=a[e],h=0;h<f.scanOrder.length;h++)if(void 0!=
c[f.scanOrder[h]]&&(c[f.scanOrder[h]](f),c.c))return $dv&&$dv.eventBus&&$dv.eventBus.dispatchEvent&&$dv.eventBus.dispatchEvent(window,"avsAdFound",{timeStamp:(new Date).getTime(),adDomElement:c.c}),c.c;return d};return this}
function dv_CustomClientViewAssureService(a){function f(a){return{qf:{adView:a.rq.av,Ne:a.rq.ic,zc:a.rq.adc,$e:a.rq.mla,cd:a.rq.ldav,focus:a.rq.fc,Ac:a.rq.as},pf:{ed:d(a.rp.mt),hf:d(a.rp.pt),bf:d(a.rp.mr),gf:d(a.rp.pr),eventId:a.rp.eid,Fc:a.rp.bl}}}function d(a){return"string"==typeof a?Array(a):a}this.Ud=dv_InViewService;this.Ud(a);this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this.b=new P;this.ab=[];a=$dv.tags[$uid].dc||a.dc||[];var h=this.b.Mc().bgm,k;for(k in a)a.hasOwnProperty(k)&&
this.ab.push(new window.Xb.ee(f(a[k]),h));var m=this.Jb;this.Jb=function(a){a=m(a);for(var c=0;c<this.ab.length;c++)this.ab[c].ge(a,this.U.interval);return a};var u=this.Oa;this.Oa=function(a,c){var d={};u(a,c);if(1==this.Ub){for(var f=0;f<this.ab.length;f++){var h=this.ab[f].df(),b;for(b in h)h.hasOwnProperty(b)&&(d[b]=h[b])}$dv.registerEventCall($uid,d)}}}window.Xb=window.Xb||{};
window.Xb.ee=function(a,f){function d(a){a.s&&a.s.f&&a.s.f.j&&a.s.f.o&&242500<=a.s.f.o*a.s.f.j&&(m=!0,h.cd&&(h.adView=h.cd),d=function(){})}var h=a.qf,k=a.pf,m=!1;this.ge=function(a,f){d(a);var k=!0,m;m=h.focus?a.m:a.ia;h.adView&&h.adView>m&&(k=!1);h.Ac&&a.s&&a.s.f&&a.s.f.j&&a.s.f.o&&a.s.f.o*a.s.f.j<h.Ac&&(k=!1);k?u+=f:h.Ne&&(u=0);this.Zd(a)};var u=0;this.df=function(){return this.lf(k.ed,k.bf,k.Fc)};this.kd=function(){this.mf(k.ed,k.hf,k.gf,k.Fc,k.eventId);this.kd=function(){}};this.Zd=function(a){(h.zc&&
u>=h.zc||m&&h.$e)&&this.kd(a)};var q;this.lf=function(a,d,h){var k={};if(f&&h)return k;if(a)for(q=$dv.tags[$uid].getTimeDiff(),h=0;h<a.length;h++)k[a[h]]=q;if(d)for(h=0;h<d.length;h++)$dv.pubSub.publish(d[h],$uid),window&&$dv.pubSub.publish(d[h],window.$frmId);return k};this.mf=function(a,d,h,k,b){if(!f||!k){if(d){k={};for(var e=$dv.tags[$uid].getTimeDiff(),l=0;l<d.length;l++)k[d[l]]=e;b&&(k.evid=b);if(a)for(l=0;l<a.length;l++)k[a[l]]=q||$dv.tags[$uid].getTimeDiff();$dv.registerEventCall($uid,k)}if(h)for(l=
0;l<h.length;l++)$dv.pubSub.publish(h[l],$uid),window&&$dv.pubSub.publish(h[l],window.$frmId)}}};function ba(){var a=!1,f=!1,d=0,h=0,k=!1;this.update=function(m,u,q,c){k||(u?(a=!0,0<q?(f=!0,q>=(m?30:50)?(h+=c,d+=c,1E3<=d&&(k=!0)):d=0):d=0):d=0)};this.De=function(){return k?6:a?f?0==h?3:1E3>h?4:1E3>d?5:6:2:1}}
function dv_InViewService(a){function f(){null===m.interval&&(m.interval=setInterval(m.xe(),m.U.interval))}function d(){if(!1===m.$c){m.$c=!0;try{m.b.Ja.remove("load",arguments.callee,!1,element)}catch(a){}m.Bb();m.b.a("s41");m.ra=new W(m.Yd?m.Yd:m.window,m.c,m.R,m.M,m.N,m.g.Hc,m.dvObj,m.impressionId);m.b.a("s42");m.Hd();m.start()}}function h(a,b){return a.isReportingDisabled?new S:new R(a,b)}function k(a,b){m.b.Ja.add("click",function(){m.Nb(!0);$dv.registerEventCall(m.impressionId,"ad"==b?{dvp_csad:1}:
{dvp_csifr:1});m.b.Ja.remove("click",arguments.callee,!1,a)},!1,a,!1)}var m=this;this.dd=10;this.Td=a.serverSettings&&a.serverSettings.jsVersion?a.serverSettings.jsVersion:"680";this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this._minor_version="0";this.b=new P;this.Ke=function(){for(var a=document.getElementsByTagName("script"),b=a.length,d,c=0;c<b;c++)if(d=a[c].src,/visit[.]js/.test(d))return d.substring(d.indexOf("?")+1)};this.$c=!1;this.fd=new ba;var u=!1,q=!1;this.He=
function(){var a="";this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].tagElement&&(a=this.dvObj.tags[this.impressionId].tagElement.src,a=a.substring(a.indexOf("?")+1));return a};this.Rc=function(){return((new Date).getTime()+""+Math.floor(1E6*Math.random())).substr(0,16)};this.V=function(a,b){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var d=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec("?"+b);return d=d?d[1]:null};this.Ie=function(){var a=this.V("uid",
this.aa);null==a?(a=this.Rc(),this.aa=this.aa+"&uid="+a):""==a&&(a=this.Rc(),this.aa=this.aa.replace("&uid=","&uid="+a));return a};this.pc=function(a,b,d,c){if(c&&c.insertBefore&&c.firstChild&&(a=this.window.document.createElement(a))){for(var e in b)a[e]=b[e];for(e in d)a.style[e]=d[e];c.insertBefore(a,c.firstChild);return a}return null};this.Xd=function(){var a=this.dvObj.Enums.TrafficScenario;try{if(window.top==window)return a.OnPage;if(window.top.document.domain==window.document.domain)return a.SameDomain}catch(b){}return a.CrossDomain};
this.R=this.dvObj.CommonData.Scenario||this.Xd();this.M={Y:this.dvObj.CommonData.BrowserId,sa:this.dvObj.CommonData.BrowserVersion};this.Z=this.dvObj.Enums.BrowserId;this.W=this.dvObj.Enums.TrafficScenario;this.Ya="default";this.dataObj=a;this.window=a.tagWindow||parent.window||window;this.c=null;this.tc=this.Pa=!1;this.mc=!0;this.interval=null;this.aa=this.Ke();this.Aa=this.He();a.serverSettings&&a.serverSettings.protocol&&a.serverSettings.protocol.indexOf("http");this.U=window.ie||this.window.ie||
{interval:100,ya:{"default":{time:null,Ja:["beforeunload","unload"],ud:9E5}}};this.jd={};var c=null;this.T=window.he||this.window.he||{interval:1E3,$:6};var n=a&&a.wd?a.wd:!1;a=a&&a.xd?a.xd:!1;!1!==n&&!1!==a&&(this.T.interval=n,this.T.$=a,$dv.registerEventCall(this.impressionId,{Of:this.T.interval,Pf:this.T.$}));n=this.b.Va();this.be={ib:12,Wb:10,Xa:30};this.N={Firefox:{X:115},Chrome:{X:89},Safari:{X:38},Explorer:{X:55},ef:500,Va:n,Xa:30};var w=!1,x=0,b=[5,10,15];window.devicePixelRatio&&(this.N.Firefox.X=
0);this.dataObj.spotXmode=this.dataObj.videoEnable||this.dataObj.detectVideoPlayer||this.dataObj.spotXmode;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].spotXmode&&(this.dataObj.spotXmode=this.dvObj.tags[this.impressionId].spotXmode);this.ja=window.dv_configAdSize||this.window.dv_configAdSize||[{w:300,h:[100,250,268,600,618,850,1050,413,50,31]},{w:160,h:[600,800]},{w:120,h:[60,90,240,600,800,20]},{w:970,h:[66,90,250,30,415,550]},{w:728,h:[90,120]},
{w:88,h:[31]},{w:700,h:[500]},{w:250,h:[60,250,300,360,600]},{w:180,h:[150,160,600]},{w:234,h:[60]},{w:468,h:[60]},{w:550,h:[480]},{w:125,h:[125]},{w:336,h:[280,600,850]},{w:745,h:[90]},{w:954,h:[60]},{w:184,h:[90]},{w:800,h:[600]},{w:320,h:[360,50,100,480,320]},{w:1280,h:[100]},{w:640,h:[480,90,360]},{w:270,h:[460,202]},{w:613,h:[460]},{w:405,h:[303]},{w:950,h:[90]},{w:610,h:[100]},{w:272,h:[220]},{w:200,h:[200,446,90]},{w:220,h:[90]},{w:240,h:[133,400]},{w:960,h:[90]},{w:580,h:[400]},{w:750,h:[100,
200,30]},{w:930,h:[180,600]},{w:980,h:[90,120]},{w:900,h:[240]},{w:275,h:[300]},{w:600,h:[400]},{w:168,h:[28]},{w:216,h:[36]},{w:292,h:[30]}];this.dataObj.spotXmode&&(this.ja.push({w:320,h:[240]}),this.ja.push({w:400,h:[300]}),this.ja.push({w:450,h:[338]}),this.ja.push({w:600,h:[800]}),this.ja.push({w:640,h:[360]}),this.ja.push({w:854,h:[480]}),this.ja.push({w:500,h:[375]}));this.pb=this.Ie();this.Vb=!1;this.Na=function(a,b){this.window.Kc||(this.window.Kc=[]);this.window.Kc.push({caller:a,Rf:b})};
this.startTime=(new Date).getTime();this.Rd=4;this.xc=0;this.gc=!0;this.logEvents={startMeasure:1,nonMeasurable:2,timeout:3,beforeunload:4,iabViewable:5,iabCustom:6,updateRTN:7,unload:8,errorlevel1:16,Mf:17,interval:32};this.Ub=!1;this.vd=function(){this.b.a("ie16");if(this.window.dv_logObject){var a=this.g.re();this.window.dv_logObject[this.pb]=a}this.b.a("ie16e")};this.Db=function(a){this.b.a("ie17");this.Db=this.Vb?function(a){this.g.pd(a);this.vd()}:function(a){this.g.pd(a)};this.Db(a)};this.sc=
function(a,b){this.sc=this.Vb?function(a,g){this.g.od(a,g);this.vd()}:function(a,g){this.g.od(a,g)};this.sc(a,b)};this.Bb=function(){this.b.a("s4");this.c=this.Qb.le(this.T.$);!this.c&&this.R==this.W.CrossDomain&&this.b.ua(this.window)&&(this.T.$=0);if(this.c)this.vf(),this.g.kf(this.c),u||(k(this.c,"ad"),u=!0),q||this.R!=this.W.CrossDomain&&this.R!=this.W.SameDomain||(k(window.parent,"ifr"),q=!0),setTimeout(f,this.Qb.jc?10:50);else if(0<this.T.$)this.T.$--,this.wf(),setTimeout(this.me(),this.T.interval);
else{try{this.R==this.W.CrossDomain&&(this.b.ad(this.window,this.ja)||this.b.ua(this.window))?(this.c=this.b.xa(this.window),this.g.nd()):this.R==this.W.SameDomain&&this.b.ad(this.window,this.ja)?(this.c=this.b.xa(window.parent),this.g.nd(),this.ae()):this.T.$=-1}catch(a){this.T.$=-1}setTimeout(f,10)}this.b.a("s4e")};this.ae=function(){for(var a=this.window;a.parent!=a.top;)a=a.parent;this.b.a("ff26");for(var b=a.parent.document.getElementsByTagName("iframe"),d=b.length,c=0;c<d;c++)b[c].contentWindow==
a&&(this.c=b[c],this.window=a.parent);this.b.a("ff26e")};this.wf=function(){this.dataObj.btreg&&this.dataObj.Qa?this.g.Af():this.g.Bf()};this.vf=function(){this.b.a("s9");this.Pa=!0;this.g.xf();this.b.a("s9e")};this.Sd=function(){this.dataObj.eb=this.V("adsrv",this.aa)||"";this.dataObj.btreg=this.V("btreg",this.aa)||"";this.dataObj.gd=this.V("plcid",this.aa)||"";"8"==this.dataObj.eb&&""==this.dataObj.btreg&&(this.dataObj.btreg=this.dataObj.plcid);this.dataObj.Qa=this.V("btadsrv",this.aa)||"";this.dataObj.Bc=
this.V("adid",this.aa)||"";this.dataObj.pb=this.pb;this.dataObj.Ve=this.V("isbtregex",this.Aa)||"";this.dataObj.kb=this.V("ctx",this.aa)||"";this.dataObj.jb=this.V("cmp",this.aa)||"";this.dataObj.We=this.V("lomd",this.Aa)||"";this.dataObj.findclass=this.V("findclass",this.Aa)||"";this.dataObj.displaynon=this.V("displaynon",this.Aa)||"";this.dataObj.Gc=this.V("bsdvview",this.Aa)||"";var a=this.V("bttag",this.Aa)||"";this.dataObj.hb=0<a.length?a.split("|"):[];a=this.V("btattb",this.Aa)||"";this.dataObj.Ia=
0<a.length?a.split("|"):[]};this.hd=function(a){a=this.xb(a);return 0<a.length?{tagServiceResult:a.join(",")}:{}};this.xb=function(a){if(!this.dvObj)return[];for(var b=[],d=0;d<a.length;d++){var c=this.dvObj.pubSub.publish(a[d],this.impressionId)||null;null!=c&&b.push(c);window&&(c=this.dvObj.pubSub.publish(a[d],window.$frmId)||null,null!=c&&b.push(c))}return b};this.Ad=function(){this.dataObj.serverSettings&&this.dataObj.serverSettings.TKH&&(this.aa+="&TKH="+this.dataObj.serverSettings.TKH)};this.fe=
function(){Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=Object(this),d=b.length>>>0;if(0===d)return-1;var c=0;1<arguments.length&&(c=Number(arguments[1]),c!=c?c=0:0!=c&&Infinity!=c&&-Infinity!=c&&(c=(0<c||-1)*Math.floor(Math.abs(c))));if(c>=d)return-1;for(c=0<=c?c:Math.max(d-Math.abs(c),0);c<d;c++)if(c in b&&b[c]===a)return c;return-1}};this.inViewManager=function(){try{Array.prototype.indexOf||this.fe();this.Ad();this.Sd();this.g=new G(this.Td,this.be,this.dataObj);
this.ga=h(this.dataObj,this.g);this.dataObj.isRTNsDisabled&&(this.xb=function(){return[]});this.Vb=this.window.dv_logObject?!0:!1;this.Cf();this.Wd=new aa(this.dataObj,this.window,this.c,this.R,this.W,this.dvObj);this.Qb=new X(this.dataObj,this.ja,this.window,this.g,this.R,this.Wd);var a=window.parent;"589953"==this.dataObj.kb&&"587351"==this.dataObj.jb||"589953"==this.dataObj.kb&&"616389"==this.dataObj.jb||"polite"==this.dataObj.We?(setTimeout(d,15E3),this.b.Ja.add("load",function(){setTimeout(d,
1E3)},!1,a,!1)):d()}catch(b){var c=this;this.Ea(function(){c.Na("inViewManager",b);c.g.$a("inViewManager",b);c.ga.ba(c.logEvents.errorlevel1)},"inViewManager",b)}};this.bb=function(a){this.b.a("ie20");-6!=a.m&&(-3==a.m||-5!=a.m&&0>a.m&&-1==this.T.$)&&(this.uc(),this.bb=function(){})};this.uc=function(){this.ga.ba(this.logEvents.nonMeasurable);this.xb(["IABNotMeasuredImpression"]);this.uc=function(){}};this.Oa=function(a,b){a.b.a("ie21");if(0<=b.m||-5==b.m&&-1>=a.T.$){if(a.dvObj&&a.impressionId){a.b.a("ie23");
var c=a.hd(["IABMeasuredImpression"]);a.b.a("ie24");a.ga.ba(a.logEvents.startMeasure,c)}else a.ga.ba(a.logEvents.startMeasure);a.Ub=!0;a.Oa=function(){};a.bb=function(){}}a.b.a("ie22")};this.Nb=function(a){this.b.a("ie25");if(this.g.Nc()||a&&!0===a)this.b.a("ie27"),this.dvObj&&this.impressionId?(this.b.a("ie28"),a=this.hd(["IABViewableImpression"]),this.b.a("ie29"),this.ga.ba(this.logEvents.iabViewable,a)):this.ga.ba(this.logEvents.iabViewable),w=!0,this.Nb=function(){};this.b.a("ie26")};this.ce=
function(a){if(w&&this.g.Nc())for(x+=a,a=0;a<b.length;a++)null!=b[a]&&x>=1E3*b[a]&&(this.xb(["IABAdViewable"+b[a]+"Seconds"]),b[a]=null);else x=0};var e="hidden",l=0;this.hasFocus=function(){vis=["hidden","webkitHidden","mozHidden","msHidden","oHidden"];for(var a in vis)if(vis[a]in document){e=vis[a];break}a=1==this.b.mb("fcs");var b=!1;try{this.b.Ta(this.window),b=!0}catch(c){}var d=!1;try{this.b.Ta(this.window.top),d=!0}catch(c){}var f=null,f=a&&b&&this.M.Y==this.Z.IE?function(){var a=m.b.Ta(m.window);
m.R==m.W.OnPage&&(a=a&&m.mc);return a}:a&&d?function(){var a=!0,a=m.b.Ta(m.window.top);m.R==m.W.OnPage&&(a=a&&m.mc);return a}:"undefined"!==typeof document[e]?function(){return!m.window.document[e]}:d?function(){return m.b.Ta(m.window.top)}:function(){return!0};this.hasFocus=function(){try{return f()}catch(a){l++,5<=l&&(this.hasFocus=function(){return!0})}return!0};return this.hasFocus()};this.cc=function(a){var b=a.ra.ve();a.b.a("ie12");null==this.c||-3==b.m||a.hasFocus()||(b.m=0);a.b.a("ie13");
return c=b};var v;this.Jb=function(a){var b;try{$uid&&dvObj&&dvObj.tags[$uid]&&dvObj.tags[$uid].getTimeDiff&&(b=dvObj.tags[$uid].getTimeDiff())}catch(c){}a.U.interval=b-v||100;v=b;a.b.a("ie1");b=a.c?a.c.qb||a.window:a.window;a.ra.c=a.c;a.ra.window=b;a.b.a("ie2");b=a.cc(a);a.Pa&&(-1==b.m||-2==b.m)&&-1<=a.T.$&&(a.ld(a),a.Bb());a.b.a("ie3");-5==b.m&&(a.T.$--,a.g.qd(),a.Ma||(a.Ma=function(b){b=a.ra.sb(b);a.g.Za(b)}));a.b.a("ie4");a.Ma&&0<b.m&&(a.Ma(b),a.Ma=null);a.b.a("ie5");if(a.Pa&&!a.tc){a.tc=!0;var d=
a.ra.sb(b);a.g.Za(d)}-5==b.m&&-1<=a.T.$&&(a.ld(a),a.Bb(),b=a.cc(a),-5==b.m&&0<a.T.$&&a.g.sf());a.b.a("ie6");a.sc(b,a.U.interval);a.fd.update(b.O,a.hasFocus(),b.m,a.U.interval);a.g.Ef(a.fd.De());a.b.a("ie7");a.Db(b);a.b.a("ie8");a.g.sd(b.da);a.bb(b);a.b.a("ie9");a.Oa(a,b);a.b.a("ie10");a.Nb();a.b.a("ie11");a.ce(a.U.interval);a.b.a("ie12");return b};this.ld=function(a){a.Pa=!1;a.c=null;a.Qb.rf();a.ra.Le()};this.xe=function(){this.b.a("s26");var a=this;return function(){try{a.Jb(a)}catch(b){a.Ea(function(){a.xc<
a.Rd&&(a.xc++,a.Na("getIntervalCallback",b),a.g.$a("getIntervalCallback",b),a.ga.ba(a.logEvents.errorlevel1))},"getIntervalCallback",b)}}};this.Qc=function(a){var b=this;return function(){b.Ea(function(){b.ga.ba(b.logEvents[a])},"getReportEventCallback")}};this.me=function(){var a=this;return function(){a.Ea(function(){a.Bb();a.c||a.g.Cb()},"getAdLocateCallback")}};this.Sa=function(){var a=this;return function(b){try{b||(b=a.window.event),a.mc="blur"==b.type||"focusout"==b.type?!1:!0}catch(c){a.Ea(function(){a.Na("getFocBluEventCallback",
c);a.g.$a("getFocBluEventCallback",c);a.ga.ba(a.logEvents.errorlevel1)},"getFocBluEventCallback",c)}}};this.Gd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this;this.dvObj.tags[this.impressionId].getViewabilityData=function(){try{for(var b=a.g.se().slice(0),c=0;c<b.length;c++)void 0===b[c]||null===b[c]?b[c]=0:isNaN(b[c])||(b[c]/=1E3);var d={};d.bucket_0=b[0];d.bucket_1_9=b[1];d.bucket_100=b[11];for(c=2;10>=c;c++)d["bucket_"+(10*(c-1)).toString()+"_"+(10*
c-1).toString()]=b[c];return{buckets:d,isAdMeasureable:a.Ub,totalPageTime:(a.g.$b()-a.g.Ge())/1E3,notApplicableTime:a.g.Pc()/1E3}}catch(e){return{}}}}}catch(b){}};this.Hd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this.dvObj.tags[this.impressionId];a.VA||(a.VA={});a.VA.getVisibilityResult=function(){var a={};a.perc=c.m;0<=c.m&&c.s&&c.s.f&&(a.adWidth=c.s.f.o,a.adHeight=c.s.f.j);return a};a.VA.getAdElem=function(){return m.c}}}catch(b){}};this.Gd();this.start=
function(){this.b.a("s35");this.ff(this);var a;this.U&&this.U.ya&&this.U.ya[this.Ya]&&(a=this.U.ya[this.Ya].Ja);if(a)for(var b=a.length,c=0;c<b;c++)this.jd[a[c]]=this.Qc(a[c]),this.Ha(this.window,a[c],this.jd[a[c]]);this.Ff();this.U&&this.U.ya&&this.U.ya[this.Ya]&&this.U.ya[this.Ya].ud&&setTimeout(this.nf(),this.U.ya[this.Ya].ud)};this.nf=function(){var a=this;return function(){a.Qc("timeout")();clearInterval(a.interval);a.ga.ba=function(){}}};this.ff=function(a){try{var b=a.cc(a);-5==b.m&&(this.g.qd(),
this.Ma||(this.Ma=function(b){b=a.ra.sb(b);a.g.Za(b)}));if(a.Pa)if(this.tc=!0,-5!=b.m){var c=a.ra.sb(b);a.g.Za(c)}else a.g.Za("true");a.g.sd(b.da);var d=a.ra.oe(b,a.g.Pc());a.g.zf(d);a.g.rd(b.m);a.Db(b);a.bb(b);a.Oa(a,b)}catch(e){a.Ea(function(){a.Na("onStartReport",e);a.g.$a("onStartReport",e);a.ga.ba(a.logEvents.errorlevel1)},"onStartReport",e)}};this.Ff=function(){this.Ha(this.window,"blur",this.Sa());this.Ha(this.window,"focus",this.Sa());this.Ha(this.window.document,"click",this.Sa());this.Ha(this.window.document,
"mousedown",this.Sa());this.Ha(this.window.document,"mouseup",this.Sa())};this.Ha=function(){function a(b,c,d){a=b.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a(b,c,d)}return function(b,c,d){a(b,c,d)}}();this.stop=function(){};this.Cf=function(){this.b.a("ff24");this.R==this.W.CrossDomain?this.b.ua(this.window)||this.b.kc(this.window)||this.b.tb()||this.b.ub(this.R,this.M,this.dvObj)||(this.M.Y!=this.Z.Firefox&&
this.M.Y!=this.Z.IE?this.g.Df():this.M.Y==this.Z.Firefox&&"undefined"===typeof this.window.mozInnerScreenX&&this.g.qc()):window.document.body.getBoundingClientRect||this.g.qc();this.gc=this.g.Hc();this.b.a("ff24e")};this.Ea=function(a,b,c){try{a()}catch(d){try{0<this.dd&&(this.dd--,a=c||d,b=b||"unknown caller",this.Na(b,a),this.g.$a(b,a),this.ga.ba(m.logEvents.errorlevel1))}catch(e){}}};return this}
try{window.dv_InViewService=dv_InViewService;dv_InViewService.prototype.inViewManager=dv_InViewService.prototype.inViewManager;var ViewAssureBootstrapper=function(a){(new dv_CustomClientViewAssureService(a)).inViewManager()};if("function"===typeof window.IVCallback)IVCallback(ViewAssureBootstrapper);else for(var Y=[window.$dvbs,window.$dvbsr],Z=0;Z<Y.length;Z++){var dvObj=Y[Z];if(dvObj&&"object"===typeof dvObj&&"function"===typeof dvObj.getTagObjectByService){var tagObject=dvObj.getTagObjectByService("avs680");
if(tagObject){var serviceParams=tagObject.services.avs680;serviceParams&&serviceParams.params&&ViewAssureBootstrapper(serviceParams.params)}}}}catch(a){};
